### PR TITLE
Cleanup

### PR DESCRIPTION
**Pull request by Cabalist**
Hey there.  I am still reading through this code.  I did another batch of PEP8 fixes.  This code is all formatting changes and some light ambiguity fixes.

Add File encoding. Whitespace.  Order imports and replace import *.  Remove redundant parentheses.  Replace int(750) -> 750.  Rename Shadowed builtins.   Remove unused variables

### CODE REVIEW

**Comment by oskay** [comment]
For the record, I strongly disagree with (but grudgingly accept) PEP8's guidance on the preference of spaces over tabs. 

Is there a reason for the change of `str` to `str_`? I don't see that there is (for example) an obvious keyword that this is conflicting with, nor other ambiguity, nor PEP8 reason for the change.

**Comment by Cabalist** [comment]
@oskay  haha  I hear you.  PEP8 is a suggestion not a requirement and tabs and spaces are easily swapped between.  I'm not going to fight you on your project.  ;)  Your call.  

`str` is a reserved keyword in python.  i.e  `str(8)` returns `'8'` overriding it prevents `str()` calls in that namespace.

**Comment by oskay** [comment]
Huh. Didn't show up in the usual list of python keywords, but sure enough.

**Comment by oskay** [comment]
Thank you!

**Pull request merged**
