### PR TITLE
Compatibility with python 3 and inkscape

### PR DESCRIPTION
**Pull request by shoshber**

### CODE REVIEW

**Comment by oskay** [comment]
Please use  a different name other than axidraw_utils-- maybe plotink_utils? These are intended to be utilities used by several of our machines (including AxiDraw).

**Comment by shoshber** [comment]
How about "plot_import_utils"? I think that differentiates it from plot_utils better

**Comment by oskay** [comment]
Sure.

**Comment by oskay** [comment]
Though; that does seem to imply that it's about importing artwork.

**Comment by oskay** [comment]
plot_utils_import?

**Pull request merged**
